"""Unpack the student release and render its notebooks in fresh R processes."""
from pathlib import Path
import os,subprocess,tempfile,zipfile
root=Path(__file__).resolve().parents[1]
env=os.environ.copy()
if (root/'.learnr-library').exists(): env['R_LIBS_USER']=str((root/'.learnr-library').resolve())
pandoc=Path('/Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/aarch64')
if (pandoc/'pandoc').exists(): env.setdefault('RSTUDIO_PANDOC',str(pandoc))
with tempfile.TemporaryDirectory(prefix='statistics-student-') as td:
 with zipfile.ZipFile(root/'statistics_lab_student.zip') as z:
  assert z.testzip() is None
  z.extractall(td)
 project=next(Path(td).iterdir())
 assert (project/'Statistics_lab.Rproj').is_file()
 assert not (project/'data/source').exists()
 for name in ['03_statistical_analysis','04_investigation']:
  subprocess.run(['Rscript','--vanilla','-e',f'rmarkdown::render("notebooks/{name}.Rmd",quiet=TRUE)'],cwd=project,env=env,check=True)
 # A complete learnr export generated by validate.R must also work in this separate copy.
 export=root/'outputs/validation_export.Rmd'
 if not export.exists(): raise RuntimeError('Run Rscript scripts/validate.R before validating the ZIP.')
 (project/'notebooks/validation_export.Rmd').write_bytes(export.read_bytes())
 subprocess.run(['Rscript','--vanilla','-e','rmarkdown::render("notebooks/validation_export.Rmd",quiet=TRUE)'],cwd=project,env=env,check=True)
 for name in ['03_statistical_analysis','04_investigation','validation_export']:
  text=(project/'notebooks'/f'{name}.html').read_text()
  assert 'Error in' not in text
print('PASS: independent student ZIP; two notebooks and completed learnr export render in fresh R sessions.')
